---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-credentials
  namespace: microservice-b
  annotations:
    tekton.dev/docker-0: https://harbor.YOUR_DOMAIN/v2/
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice-b
  namespace: microservice-b
secrets:
- name: harbor-credentials
