---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
  namespace: microservice-a
  labels:
    app.kubernetes.io/instance: microservice-a
    app.kubernetes.io/part-of: microservice-a
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: app
spec:
  replicas: 2
  selector:
    matchLabels:
      service: microservice-a
      role: app
  template:
    metadata:
      labels:
        service: microservice-a
        role: app
    spec:
      serviceAccountName: microservice-a
      containers:
        - name: microservice-a
          image: registry-harbor-core.harbor.svc.cluster.local/library/microservice-a:241f51d8ff3d2496b09e1066a5bc3856080c87dd
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-a
  namespace: microservice-a
  labels:
    app.kubernetes.io/instance: microservice-a
    app.kubernetes.io/part-of: microservice-a
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    service: microservice-a
    role: app




